--------------------------------------------------------------------------------
-- ГОТОВЫЕ ЗОНЫ ГОРОДОВ
--------------------------------------------------------------------------------
-- Этот файл только для заранее прописанных зон. Зоны с F11 живут в БД
-- и сюда не попадают.
--
-- Добавить зону  — скопируй любой блок ниже и смени id.
-- Выключить      — enabled = false
-- Удалить        — сотри весь блок { ... },
--
-- coords  — центр
-- radius  — игрок на подходе (radius + approachPadding) = спавн в центре
-- count   — сколько зомби держать в зоне
-- spread  — кольцо спавна после первой волны, метры
-- models  — Config.Models или Config.ColterModels
--------------------------------------------------------------------------------

Config.Zones = {
    {
        id = "colter",
        label = "Колтер",
        enabled = true,
        coords = vector3(-1344.0, 2425.0, 307.0),
        radius = 90.0,
        count = 22,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 85.0 },
        maxSpawnHeightDiff = 8.0,
        models = Config.ColterModels,
    },
    {
        id = "valentine",
        label = "Валентайн",
        enabled = true,
        coords = vector3(-283.0, 779.0, 119.0),
        radius = 95.0,
        count = 40,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 90.0 },
        maxSpawnHeightDiff = 5.0,
        models = Config.Models,
    },
    {
        id = "strawberry",
        label = "Строуберри",
        enabled = true,
        coords = vector3(-1798.0, -385.0, 160.0),
        radius = 70.0,
        count = 22,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 65.0 },
        maxSpawnHeightDiff = 6.0,
        models = Config.Models,
    },
    {
        id = "blackwater",
        label = "Блэкуотер",
        enabled = true,
        coords = vector3(-813.0, -1317.0, 43.0),
        radius = 110.0,
        count = 45,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 105.0 },
        maxSpawnHeightDiff = 4.0,
        models = Config.Models,
    },
    {
        id = "rhodes",
        label = "Роудс",
        enabled = true,
        coords = vector3(1345.0, -1298.0, 77.0),
        radius = 90.0,
        count = 35,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 85.0 },
        maxSpawnHeightDiff = 5.0,
        models = Config.Models,
    },
    {
        id = "saintdenis",
        label = "Сен-Дени",
        enabled = true,
        coords = vector3(2632.0, -1312.0, 52.0),
        radius = 170.0,
        count = 70,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 165.0 },
        maxSpawnHeightDiff = 6.0,
        models = Config.Models,
    },
    {
        id = "annesburg",
        label = "Аннесбург",
        enabled = true,
        coords = vector3(2930.0, 1278.0, 44.5),
        radius = 85.0,
        count = 28,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 80.0 },
        maxSpawnHeightDiff = 8.0,
        models = Config.Models,
    },
    {
        id = "vanhorn",
        label = "Ван-Хорн",
        enabled = true,
        coords = vector3(2963.0, 528.0, 44.0),
        radius = 70.0,
        count = 22,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 65.0 },
        maxSpawnHeightDiff = 5.0,
        models = Config.Models,
    },
    {
        id = "armadillo",
        label = "Армадилло",
        enabled = true,
        coords = vector3(-3685.0, -2606.0, -14.0),
        radius = 75.0,
        count = 24,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 70.0 },
        maxSpawnHeightDiff = 4.0,
        models = Config.Models,
    },
    {
        id = "tumbleweed",
        label = "Тамблвид",
        enabled = true,
        coords = vector3(-5508.0, -2947.0, -1.8),
        radius = 80.0,
        count = 24,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 75.0 },
        maxSpawnHeightDiff = 4.0,
        models = Config.Models,
    },
    {
        id = "emerald",
        label = "Эмеральд-Ранчо",
        enabled = true,
        coords = vector3(1418.0, 321.0, 89.0),
        radius = 70.0,
        count = 18,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 65.0 },
        maxSpawnHeightDiff = 5.0,
        models = Config.Models,
    },
    {
        id = "lagras",
        label = "Лаграс",
        enabled = true,
        coords = vector3(2111.0, -620.0, 42.0),
        radius = 55.0,
        count = 16,
        spawnAcrossZone = true,
        spread = { min = 5.0, max = 50.0 },
        maxSpawnHeightDiff = 4.0,
        models = Config.Models,
    },
}
