CREATE TABLE IF NOT EXISTS `thehunt_animation_favorites` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `identifier` VARCHAR(64) NOT NULL UNIQUE,
  `favorites` LONGTEXT NOT NULL DEFAULT '[]',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
