-- =================================================================
-- HUNT: Hard RP — Obsidian Animations & Emotes Configuration
-- Verified and aligned with RSG-Animations & Femga Discoveries
-- =================================================================

Config = {}

Config.Command = 'anim'
Config.OpenKey = 0x1F6D95E5 -- F3
Config.CancelKey = 0xA65EBAB4 -- F1
Config.CancelCommand = 'stopanim'

-- Hold N to point forward. This is a looping upper-body clip so locomotion
-- and horse riding keep their normal lower-body tasks.
Config.PointingAnimation = {
    enabled = true,
    dict = 'ai_react@point@base',
    body = 'point_fwd',
    -- The stock pointing set has a compatible right-hand upward variant.
    -- Below the horizon we keep the same stable forward pointing pose because
    -- the other stock downward gestures are unrelated one-shot gestures.
    vertical = {
        enabled = true,
        upBody = 'point_up_fwd',
        threshold = 0.32,
        switchCooldown = 260
    },
    -- Experimental RDR2 arm IK.  The animation remains as a safe fallback;
    -- if this native is unavailable or rejects the call, N still works with
    -- the verified clips above.
    ik = {
        enabled = true,
        rightArm = 4,
        targetModel = 'p_cs_shotglass01x',
        -- Position-only IK; wrist/finger pose comes from the base clip.
        targetFlags = 0,
        maxYaw = 60.0,
        crossBodyYaw = 35.0,
        maxPitchUp = 55.0,
        maxPitchDown = 50.0,
        maxAngularSpeed = 150.0,
        smoothingSeconds = 0.12,
        raiseDuration = 450,
        blendIn = 120,
        blendOut = 450,
        syncInterval = 60,
        remoteTimeout = 1500
    },
    flag = 31,
    blendIn = 2.0,
    blendOut = -2.0,
    reapplyDelay = 700,
    mounted = {
        dict = 'script_story@fud1@ig@ig_horseback_pointing',
        body = 'right_hand_point_01',
        flag = 31,
        blendIn = 2.0,
        blendOut = -2.0,
        reapplyDelay = 700
    }
}

Config.Categories = {
    { id = 'All', label = 'Все', icon = 'fas fa-th' },
    { id = 'Poses', label = 'Позы', icon = 'fas fa-user-tie' },
    { id = 'Gestures', label = 'Жесты', icon = 'fas fa-hand-paper' },
    { id = 'Emotes', label = 'Эмоции', icon = 'fas fa-smile' },
    { id = 'Dances', label = 'Танцы', icon = 'fas fa-music' },
    { id = 'Scenarios', label = 'Сценарии', icon = 'fas fa-user-clock' },
}

Config.Animations = {

    -- ################################## POSES ##################################
    {
        Label = 'Злой взгляд',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'ai_react@react_look_layers@base_emotions@angry',
        Body = 'direct',
        Flag = 31,
    },
    {
        Label = 'Замешательство',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'security_look_around@idle_c',
    },
    {
        Label = 'Скрестить руки',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'mech_skin@buck@butcher',
        Body = 'trans_to_stoic_butcher',
        Flag = 30,
    },
    {
        Label = 'Осмотреть землю',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'MP_LOBBY_WORLD_HUMAN_CROUCH_INSPECT',
    },
    {
        Label = 'Женственная поза',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'mech_loco_f@character@karen@normal@unarmed@idle',
        Body = 'idle',
    },
    {
        Label = 'Караул',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'stand_guard@idle_a',
        Flag = 1,
    },
    {
        Label = 'Руки на ремне',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'mech_loco@generic@spectator@b@streamed_idles',
        Body = 'idle_c',
        Flag = 31,
    },
    {
        Label = 'Руки в боки',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'script_amb@stores@store_waist_stern_guy',
        Body = 'base',
        Flag = 31,
    },
    {
        Label = 'Стойка ожидания',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_stand_waiting@female_a@idle_a',
        Body = 'idle_a',
        Flag = 31,
    },
    {
        Label = 'Свободная стойка',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_stand_waiting@female_a@idle_a',
        Body = 'idle_b',
        Flag = 31,
    },
    {
        Label = 'Нетерпение',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'idle_d',
    },
    {
        Label = 'Опереться о стену',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_LEAN_BACK_WALL',
    },
    {
        Label = 'Опереться о перила',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_rest_lean@world_human_lean_fence_fwd_check_out_livestock@male_e@idle_c',
        Body = 'idle_g',
        Flag = 1,
    },
    {
        Label = 'Ожидание',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'door_deal_wait_buyer',
    },
    {
        Label = 'Поникшая поза',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@emotion@unarmed@sad@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Соблазнительная поза',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_work@world_human_whore@female_a@wip_base',
        Body = 'wip_base',
        Flag = 31,
    },
    {
        Label = 'Сесть у костра',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_camp@world_camp_fire_sit_ground@male_c@idle_a',
        Body = 'idle_a',
        Flag = 1,
    },
    {
        Label = 'Присесть на землю',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'GENERIC_SIT_GROUND_SCENARIO',
    },
    {
        Label = 'Спать на земле',
        Category = 'Poses',
        Type = 'Anim',
        Dict = 'amb_rest@world_human_sleep_ground@arm@male_b@idle_b',
        Body = 'idle_f',
        Flag = 1,
    },
    {
        Label = 'Суровый взгляд',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'MP_LOBBY_WORLD_HUMAN_STARE_STOIC',
    },
    {
        Label = 'Стойка шерифа',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'MP_LOBBY_WORLD_HUMAN_STERNGUY_IDLES',
    },
    {
        Label = 'Нетерпеливое ожидание',
        Category = 'Poses',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_WAITING_IMPATIENT',
    },

    -- ################################## GESTURES ##################################
    {
        Label = 'Нетерпеливый жест',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_waiting_impatient@male_d@idle_b',
        Body = 'idle_d',
        Flag = 31,
    },
    {
        Label = 'Небрежный жест',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'drug_dealer_idle_d',
    },
    {
        Label = 'Попался',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_proc@robberies@unapproved',
        Body = 'stand_prisoner_cell_idle_a',
        Flag = 1,
    },
    {
        Label = 'Чисто',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_react@react_look_layers@base_emotions@brave',
        Body = 'direct',
    },
    {
        Label = 'Упасть от бессилия',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_story@gua2@ig@ig_walkcollapse',
        Body = 'gua2_collapse_rf',
    },
    {
        Label = 'Кашель',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_coughing@male_c@wip_base',
        Body = 'wip_base',
    },
    {
        Label = 'Прикрыться',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'windowwasher_shot_reaction',
    },
    {
        Label = 'Сжаться от страха',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@crowd_control@unapproved@a@ped_d@cower',
        Body = 'cower',
        Flag = 1,
    },
    {
        Label = 'Плакать',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'cry_loop',
        Flag = 1,
    },
    {
        Label = 'Боль 1',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@critical_ground@idle@_variations@d',
        Body = 'idle',
        Flag = 1,
    },
    {
        Label = 'Боль 2',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@critical_ground@idle@_variations@e',
        Body = 'idle',
        Flag = 1,
    },
    {
        Label = 'Скромный кивок шляпой',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@character@arthur@fidgets@hat@normal@unarmed@normal@left_hand',
        Body = 'hat_lhand_b',
    },
    {
        Label = 'Сдержанный взмах рукой',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_gestures@gen_female@standing@silent',
        Body = 'silent_flirty_greet_r_001',
    },
    {
        Label = 'Пьяное покачивание',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_drunk_dancing@male@male_a@idle_b',
        Body = 'idle_e',
    },
    {
        Label = 'Умирание',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_indian_sick_dying@male@male_a@idle_a',
        Body = 'idle_c',
        Flag = 1,
    },
    {
        Label = 'Взмах руками',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_gestures@gen_female@standing@silent@script',
        Body = 'silent_clap_f_001',
    },
    {
        Label = 'Замерзать',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_re@lost_man',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Сильный мороз',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@wave@male@unapproved',
        Body = 'wave_idle_c',
    },
    {
        Label = 'В стельку',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_re@crashed_wagon',
        Body = 'male_drunk_action',
    },
    {
        Label = 'Легкий поклон шляпой',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@character@dutch@fancy@unarmed@idle@_variations',
        Body = 'idle_b',
    },
    {
        Label = 'Руки вверх',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_f@generic@reaction@handsup@unarmed@normal',
        Body = 'loop',
        Flag = 31,
    },
    {
        Label = 'Заложник',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mini_hostage',
        Body = 'gped_host_knl_idl',
        Flag = 1,
    },
    {
        Label = 'Воодушевление',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'protest_female_idle_c',
    },
    {
        Label = 'Раненая рука',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@right_arm@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Больная спина',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@critical_back@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Ранение груди',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@chest@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Ранение головы',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@head@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Больное бедро',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@left_leg@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Боль в шее',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@injured@unarmed@critical_neck_right@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Раненое плечо',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@character@arthur@injured@left_shoulder@unarmed@idle',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Чесаться',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@special@unarmed@itchy@idle',
        Body = 'idle_intro',
        Flag = 31,
    },
    {
        Label = 'Постучать',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_door_knock@male_a@idle_c',
        Body = 'idle_h',
    },
    {
        Label = 'Хмельное состояние',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@drunk@unarmed@idle_moderate_drunk',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Скорбь',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_proc@robberies@shop@rhodes@gunsmith@inside_basement_reshoot',
        Body = 'cry_loop_captor',
    },
    {
        Label = 'Нервозность',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_rc@rmyr4@unapproved@scared',
        Body = 'idle',
        Flag = 31,
    },
    {
        Label = 'Спокойный жест',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@character@nicholas_timmins@normal@unarmed@idle@variations@big_wave',
        Body = 'idle',
    },
    {
        Label = 'Кивнуть головой',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_gestures@gen_female@standing@silent',
        Body = 'silent_neutral_greet_f_002',
    },
    {
        Label = 'Хирургия',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@service_bell@unapproved',
        Body = 'base',
    },
    {
        Label = 'Сюда',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@wave@male@unapproved',
        Body = 'wave_idle_d',
    },
    {
        Label = 'Указать вперед',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'loop_0',
        Flag = 31,
    },
    {
        Label = 'Рвота',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_vomit@male_a@idle_b',
        Body = 'idle_f',
    },
    {
        Label = 'Тише',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@character@arthur@calming@unarmed@idle',
        Body = 'idle',
    },
    {
        Label = 'Сарказм',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_gestures@gen_female@standing@silent',
        Body = 'silent_neutral_wave_r_001',
    },
    {
        Label = 'Обыск',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@other@unapproved',
        Body = 'guard_patrol@idle_e',
    },
    {
        Label = 'Тошнота',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_wander@upperbody_idles@sick@both_arms@male_a@idle_a',
        Body = 'idle_c',
    },
    {
        Label = 'Пригладить волосы',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'ai_gestures@arthur@standing@speaker@rt_hand',
        Body = 'greet_cocky_l_003',
    },
    {
        Label = 'Сдаться полиции',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_busted@unapproved',
        Body = 'idle_b',
        Flag = 1,
    },
    {
        Label = 'Вытереть пот',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@fidgets@hot',
        Body = 'both_hands_fanning_02',
    },
    {
        Label = 'Благодарность',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_common@thank@female@unapproved',
        Body = 'thank_c',
    },
    {
        Label = 'Приступ тошноты',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_vomit@male_a@idle_b',
        Body = 'idle_f',
    },
    {
        Label = 'Неловкость',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'script_story@fin2@ig@ig2_chase_cleet',
        Body = 'civilian_injured_loop_a_civilian',
    },
    {
        Label = 'Запись в гроссбух',
        Category = 'Gestures',
        Type = 'Anim',
        Dict = 'amb_work@world_human_write_notebook@female_a@idle_c',
        Body = 'idle_g',
        Flag = 1,
        Prop = { model = 'p_cs_ledgersmall01x', bone = 'SKEL_L_Hand', coords = { x = 0.05, y = 0.02, z = 0.03, rx = 0.0, ry = 0.0, rz = 0.0 } },
    },

    -- ################################## EMOTES ##################################
    {
        Label = 'Игра на банджо',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_AIR_BANJO_1',
    },
    {
        Label = 'Воздушные поцелуи',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_BLOW_KISS_1',
    },
    {
        Label = 'Изумление',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_AMAZED_1',
    },
    {
        Label = 'Злость',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_HISSYFIT_1',
    },
    {
        Label = 'Аплодисменты',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_APPLAUSE_1',
    },
    {
        Label = 'Поманить рукой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_BECKON_1',
    },
    {
        Label = 'Меткий выстрел',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_BEST_SHOT_1',
    },
    {
        Label = 'Просить пощады',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_BEGMERCY_1',
    },
    {
        Label = 'Пробовать монету на зуб',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_BITING_GOLD_COIN_1',
    },
    {
        Label = 'Хвастовство',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_BOAST_1',
    },
    {
        Label = 'Рыдания',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_BOOHOO_1',
    },
    {
        Label = 'Осторожно',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1',
    },
    {
        Label = 'Вызов на дуэль',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_VERSUS_1',
    },
    {
        Label = 'Оценить взгляд',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_CHECK_POCKET_WATCH_1',
    },
    {
        Label = 'Курица',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_CHICKEN_1',
    },
    {
        Label = 'Хлопать в такт',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_CLAP_ALONG_1',
    },
    {
        Label = 'Дразнить носом',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_COCK_SNOOK_1',
    },
    {
        Label = 'Подбросить монетку',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_COIN_FLIP_1',
    },
    {
        Label = 'Оскал пумы',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_COUGAR_SNARL_1',
    },
    {
        Label = 'Размять кулаки',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_CRUISING_BRUISING_1',
    },
    {
        Label = 'Покрутить у виска',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_CUCKOO_1',
    },
    {
        Label = 'Радостный поклон шляпой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_HAT_FLICK_1',
    },
    {
        Label = 'Рукалицо',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_FACEPALM_1',
    },
    {
        Label = 'Изящный поклон',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_FANCY_BOW_1',
    },
    {
        Label = 'Игра на скрипке',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_FIDDLEHEAD_1',
    },
    {
        Label = 'Выходи на бой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_PROVOKE_1',
    },
    {
        Label = 'Игра с револьвером',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_FINGER_SLINGER_1',
    },
    {
        Label = 'Победный кулак',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_FIST_PUMP_1',
    },
    {
        Label = 'Показать мускулы',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_FLEX_1',
    },
    {
        Label = 'Воздушный поцелуй',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_FLYING_KISS_1',
    },
    {
        Label = 'Дружеский взмах',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_SUBTLE_WAVE_1',
    },
    {
        Label = 'Напугать',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_FRIGHTEN_1',
    },
    {
        Label = 'Средний палец',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_FLIP_OFF_1',
    },
    {
        Label = 'Легкий взмах рукой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_WAVENEAR_1',
    },
    {
        Label = 'Иди сюда',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_GET_OVER_HERE_1',
    },
    {
        Label = 'Радость',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_GLAD_1',
    },
    {
        Label = 'Горилла',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_GORILLA_CHEST_1',
    },
    {
        Label = 'Рукопожатие',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_HAND_SHAKE_1',
    },
    {
        Label = 'Похмелье',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_HANGOVER_1',
    },
    {
        Label = 'Щелчок по шляпе',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_HAT_FLICK_1',
    },
    {
        Label = 'Эй ты',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_HEY_YOU_1',
    },
    {
        Label = 'Как ты смеешь',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_HOW_DARE_YOU_1',
    },
    {
        Label = 'Волчий вой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_HOWL_1',
    },
    {
        Label = 'Смирение',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_RESPECTFUL_BOW_1',
    },
    {
        Label = 'Метнуть',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_HURL_1',
    },
    {
        Label = 'Энергичный взмах',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_GENTLEWAVE_1',
    },
    {
        Label = 'Гипноз',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_HYPNOSIS_POCKET_WATCH_1',
    },
    {
        Label = 'Пришла идея',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_IDEA_1',
    },
    {
        Label = 'Ничтожество',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_INSIGNIFICANT_1',
    },
    {
        Label = 'Джига',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_PROSPECTOR_JIG_1',
    },
    {
        Label = 'Не отставай',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_FOLLOW_ME_1',
    },
    {
        Label = 'Смех',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_JOVIAL_LAUGH_1',
    },
    {
        Label = 'Насмешка',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_POINTLAUGH_1',
    },
    {
        Label = 'За дело',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LETS_CRAFT_1',
    },
    {
        Label = 'Пойдем на рыбалку',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LETS_FISH_1',
    },
    {
        Label = 'Пошли',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LETS_GO_1',
    },
    {
        Label = 'Сыграем в карты',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LETS_PLAY_CARDS_1',
    },
    {
        Label = 'Прислушаться',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LISTEN_1',
    },
    {
        Label = 'Вглядываться вдаль',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LOOK_DISTANCE_1',
    },
    {
        Label = 'Посмотри туда',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_LOOK_YONDER_1',
    },
    {
        Label = 'Хвастаться одеждой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_NEWTHREADS_1',
    },
    {
        Label = 'Кивок головы',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_NOD_HEAD_1',
    },
    {
        Label = 'Излияние чувств',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_OUTPOUR_1',
    },
    {
        Label = 'Фух',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_PHEW_1',
    },
    {
        Label = 'Указать пальцем',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_POINT_1',
    },
    {
        Label = 'Сбор отряда',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_POSSE_UP_1',
    },
    {
        Label = 'Молитва',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_PRAYER_1',
    },
    {
        Label = 'Потрошитель',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_RIPPER_1',
    },
    {
        Label = 'Камень ножницы бумага',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_ROCK_PAPER_SCISSORS_1',
    },
    {
        Label = 'Борьба',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_ROUGH_HOUSING_1',
    },
    {
        Label = 'Испуг',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SCARED_1',
    },
    {
        Label = 'Семерка',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_SEVEN_1',
    },
    {
        Label = 'Покачать головой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SHAKEHEAD_1',
    },
    {
        Label = 'Тсс',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_HUSH_YOUR_MOUTH_1',
    },
    {
        Label = 'Стрельба от бедра',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SHOOTHIP_1',
    },
    {
        Label = 'Выстрел',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SHOT_1',
    },
    {
        Label = 'Пожать плечами',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SHRUG_1',
    },
    {
        Label = 'Выстрел в воздух',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SKYWARD_SHOOTING_1',
    },
    {
        Label = 'Медленные хлопки',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SLOW_CLAP_1',
    },
    {
        Label = 'Курить сигару',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SMOKE_CIGAR_1',
    },
    {
        Label = 'Курить сигарету',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SMOKE_CIGARETTE_1',
    },
    {
        Label = 'Крадущийся',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SCHEME_1',
    },
    {
        Label = 'Принюхиваться',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SNIFFING_1',
    },
    {
        Label = 'Высморкаться',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SNOT_ROCKET_1',
    },
    {
        Label = 'Всхлипывания',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SOB_1',
    },
    {
        Label = 'Прокрутка и прицел',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SPIN_AND_AIM_1',
    },
    {
        Label = 'Плюнуть',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SPIT_1',
    },
    {
        Label = 'Жуть',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_SPOOKY_1',
    },
    {
        Label = 'Фу какая вонь',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_YOUSTINK_1',
    },
    {
        Label = 'Стой здесь',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_STOP_HERE_1',
    },
    {
        Label = 'Сдаюсь',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SURRENDER_1',
    },
    {
        Label = 'Тада',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_TADA_1',
    },
    {
        Label = 'Делать заметки',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_TAKE_NOTES_1',
    },
    {
        Label = 'Спасибо',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_THANKS_1',
    },
    {
        Label = 'Вот этот парень',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_THIS_GUY_1',
    },
    {
        Label = 'Перерезать горло',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_THROAT_SLIT_1',
    },
    {
        Label = 'Палец вниз',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_THUMBSDOWN_1',
    },
    {
        Label = 'Палец вверх',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_THUMBSUP_1',
    },
    {
        Label = 'Приподнять шляпу',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_HAT_TIP_1',
    },
    {
        Label = 'Крутой',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_GREET_TOUGH_1',
    },
    {
        Label = 'Пошел ты',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_UP_YOURS_1',
    },
    {
        Label = 'Погрозить пальцем',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_WAG_FINGER_1',
    },
    {
        Label = 'Боевой клич',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_TAUNT_WAR_CRY_1',
    },
    {
        Label = 'Промочить горло',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_ACTION_WET_YOUR_WHISTLE_1',
    },
    {
        Label = 'Иха',
        Category = 'Emotes',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_YEEHAW_1',
    },

    -- ################################## DANCES ##################################
    {
        Label = 'Неловкий танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_AWKWARD_A_1',
    },
    {
        Label = 'Застенчивый танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@awkward@a@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Канкан',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_shows@cancandance@p2',
        Body = 'cancandance_p2_fem1',
    },
    {
        Label = 'Быстрый канкан',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_re@french_artists@dance',
        Body = 'cancan_loop_female_a',
        Flag = 1,
    },
    {
        Label = 'Беззаботный танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_CAREFREE_B_1',
    },
    {
        Label = 'Веселый танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@carefree@a@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Радостный танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_REACTION_SHUFFLE_1',
    },
    {
        Label = 'Уверенный танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@confident@b@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Задорный танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@confident@b@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Бодрый танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_CONFIDENT_A_1',
    },
    {
        Label = 'Гордый танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_CONFIDENT_B_1',
    },
    {
        Label = 'Пьяный танец 1',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_DRUNK_A_1',
    },
    {
        Label = 'Пьяный танец 2',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_DRUNK_B_1',
    },
    {
        Label = 'Пьяный танец 3',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_drunk_dancing@male@male_b@idle_a',
        Body = 'idle_b',
    },
    {
        Label = 'Пьяный танец 4',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@drunk@b@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Пьяный танец 5',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@drunk@a@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Пьяный танец 6',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'amb_misc@world_human_drunk_dancing@male@male_b@idle_a',
        Body = 'idle_c',
    },
    {
        Label = 'Степенный танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_FORMAL_A_1',
    },
    {
        Label = 'Изящный танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_GRACEFUL_A_1',
    },
    {
        Label = 'Старинный танец',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_OLD_A_1',
    },
    {
        Label = 'Дикий танец 1',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_WILD_A_1',
    },
    {
        Label = 'Дикий танец 2',
        Category = 'Dances',
        Type = 'Emote',
        EmoteType = 'KIT_EMOTE_DANCE_WILD_B_1',
    },
    {
        Label = 'Танец с огнем',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_shows@firebreather@act2_p1',
        Body = 'dancer_dance',
    },
    {
        Label = 'Пляска с огнем',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@dance@fire_dance@male_a@idle_a',
        Body = 'idle_a',
        Flag = 1,
        Prop = { model = 'p_torch02x', bone = 'SKEL_R_Hand', coords = { x = 0.08, y = 0.02, z = 0.0, rx = 0.0, ry = 90.0, rz = 0.0 } },
    },
    {
        Label = 'Танец старика',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@old@a@male@unarmed@full',
        Body = 'fullbody',
    },
    {
        Label = 'Танец со змеей',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_shows@snakedancer@act1_p1',
        Body = 'dance_dancer',
    },
    {
        Label = 'Шаманский танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@dance@snake_dance@male_a@idle_a',
        Body = 'idle_a',
        Flag = 1,
    },
    {
        Label = 'Танец с саблями',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_shows@sworddance@act3_p1',
        Body = 'dancer_sworddance',
    },
    {
        Label = 'Пляска с клинками',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'mech_loco_m@generic@dance@sword_dance@male_a@idle_a',
        Body = 'idle_a',
        Flag = 1,
        Prop = { model = 'w_melee_machete01', bone = 'SKEL_R_Hand', coords = { x = 0.08, y = 0.03, z = -0.02, rx = 0.0, ry = 90.0, rz = 0.0 } },
    },
    {
        Label = 'Бешеный танец',
        Category = 'Dances',
        Type = 'Anim',
        Dict = 'script_mp@emotes@dance@wild@b@male@unarmed@full',
        Body = 'fullbody',
    },

    -- ################################## SCENARIOS ##################################
    {
        Label = 'Крутой парень',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_BADASS',
        Flag = 31,
    },
    {
        Label = 'Протирать стакан',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
    },
    {
        Label = 'Пить кофе',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_COFFEE_DRINK',
    },
    {
        Label = 'Играть на гитаре',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_SIT_GUITAR',
    },
    {
        Label = 'Стучать молотком',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_HAMMER_TABLE',
    },
    {
        Label = 'Смотреться в зеркало',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_POCKET_MIRROR',
    },
    {
        Label = 'Скорбеть у могилы',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_GRAVE_MOURNING',
    },
    {
        Label = 'Скорбеть на коленях',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_GRAVE_MOURNING_KNEEL',
    },
    {
        Label = 'Играть на трубе',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_TRUMPET',
    },
    {
        Label = 'Читать книгу на земле',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_SIT_GROUND_READING_BOOK',
    },
    {
        Label = 'Сесть на землю',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_SIT_GROUND',
    },
    {
        Label = 'Лечь на землю',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_SLEEP_GROUND_ARM',
    },
    {
        Label = 'Рыбачить',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_STAND_FISHING',
    },
    {
        Label = 'Подметать метлой',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_BROOM',
    },
    {
        Label = 'Справить нужду',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_PEE',
    },
    {
        Label = 'Смотреть в бинокль',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_BINOCULARS',
    },
    {
        Label = 'Греть руки у огня',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_FIRE_STAND',
    },
    {
        Label = 'Умыться из ведра',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_WASH_FACE_BUCKET_GROUND',
    },
    {
        Label = 'Записывать в блокнот',
        Category = 'Scenarios',
        Type = 'Scenario',
        Scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
    },
}
