ZombieConfig = {
    MaxAlive = 120, MaxEntities = 160, MaxPerZone = 40, MaxZones = 500,
    ServerTick = 1000, SpawnPerTick = 3, MaxPending = 6,
    SpawnTimeout = 20000, DespawnGrace = 120000, CorpseLifetime = 45000,
    MinSpawnDistance = 12.0, EntityKeepDistance = 240.0,
    NearTick = 250, FarTick = 1200, AIBatch = 6, PlayerCacheTick = 300,
    InfoDistance = 65.0, InfoLimit = 40,
    MaxMigrations = 3, MaxMigrationDistance = 600.0, MigrationLifetime = 300000,
    SearchTime = 12000, SoundLifetime = 6000, SoundUncertainty = 5.0,
    -- RedM head bone id, not GTA's 31086. Native HP reserve protects against body hits.
    HeadBones = { [21030] = true }, HeadshotReserve = 8000,
    Noise = { shot = 180.0, run = 25.0, walk = 7.0, action = 45.0, voice = 15.0 },
    WeaponNoise = { WEAPON_BOW = 0.12, WEAPON_BOW_IMPROVED = 0.12,
        WEAPON_RIFLE_VARMINT = 0.65, WEAPON_SHOTGUN_DOUBLEBARREL = 1.3 },
    VoiceMultiplier = 1.8, MaxNoiseDistance = 300.0,
    WeaponDamage = {
        WEAPON_MELEE_KNIFE = 10,
        WEAPON_MELEE_MACHETE = 15,
        WEAPON_MELEE_CLEAVER = 12,
        WEAPON_MELEE_HATCHET = 14,
        WEAPON_MELEE_TORCH = 8,
        knife = 10,
        machete = 15,
        cleaver = 12,
        hatchet = 14,
        torch = 8,
    },
    Profiles = {
        ordinary = { name = 'Мёртвый', health = 350, damage = 18, weaponDamage = 25, speed = 2.3,
            sight = 38, hearing = 1.0, hearingDistance = 220, aggression = 1.0, headshotOnly = false,
            attackRange = 2.4, attackCooldown = 500, reaction = 900, migration = true, walkStyle = 'MP_Style_drunk',
            models = { 'A_M_M_ArmCholeraCorpse_01', 'A_F_M_ArmCholeraCorpse_01',
                'A_M_M_UniCorpse_01', 'A_F_M_UniCorpse_01', 'RE_CorpseCart_Males_01',
                'RE_SavageAftermath_Males_01', 'RE_SavageAftermath_Females_01' } },
        sturdy = { name = 'Крепкий Мёртвый', health = 550, damage = 27, weaponDamage = 35, speed = 1.85,
            sight = 32, hearing = 1.1, hearingDistance = 240, aggression = 1.0, headshotOnly = false,
            attackRange = 2.4, attackCooldown = 700, reaction = 1200, migration = true, walkStyle = 'MP_Style_drunk',
            models = { 'CS_SwampFreak', 'U_M_M_CircusWagon_01', 'RE_SavageWarning_Males_01' } },
        hollow = { name = 'Пустой', health = 450, damage = 22, weaponDamage = 30, speed = 2.85,
            sight = 45, hearing = 1.2, hearingDistance = 280, aggression = 1.0, headshotOnly = true,
            attackRange = 2.4, attackCooldown = 400, reaction = 650, migration = true, walkStyle = 'MP_Style_drunk',
            models = { 'CS_Vampire', 'CS_MrAdler', 'U_M_M_APFDeadMan_01' } },
    }
}
